#
# Makefile.fragment
#

ACLOCAL_AMFLAGS = -I m4
INCLUDES = -Iinclude

lib_LTLIBRARIES = librattle.la
librattle_la_SOURCES =	\
	src/rattle.c
#	src/core.c	\
#	src/log.c	\
#	src/module.c	\
#	src/table.c

librattle_la_LIBADD =

include_HEADERS = include/rattle.h

pkglib_LTLIBRARIES =
EXTRA_LTLIBRARIES =
