#
# modules/proc/worker/Makefile.fragment
#

if WANT_PROC_WORKER
pkglib_LTLIBRARIES += proc_worker.la
proc_worker_la_LDFLAGS = -module -avoid-version -lpthread
proc_worker_la_SOURCES = \
	modules/proc/worker/proc_worker.c
endif
